######################################################################
# Automatically generated by qmake (3.0) Tue Jul 8 01:32:11 2014
######################################################################

TEMPLATE = app
TARGET = "qt dm"
INCLUDEPATH += .

# Input
SOURCES += main.cpp window.cpp
QT += widgets
CONFIG += c++11
LIBS += -lcrypt
