######################################################################
# Automatically generated by qmake (3.0) Tue Jul 8 01:32:11 2014
######################################################################

TEMPLATE = app
TARGET = "../../marcdm-helper"
INCLUDEPATH += .

# Input
SOURCES += main.cpp Auth.cpp SessionApp.cpp session.cpp
# QT += core
CONFIG += c++11
LIBS += -lpam -lpam_misc

OBJECTS_DIR = build
